version: '3.5'

services:

  producer:
    image: rianmachado/producer-movie:1.0
    build:
      context: producer
      dockerfile: Dockerfile.native
    environment:
      KAFKA_BOOTSTRAP_SERVERS: localhost:9092
    networks:
      - kafkastreams-network

  aggregator:
    image: quarkus-quickstarts/kafka-streams-aggregator:1.0
    build:
      context: aggregator
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS: localhost:9092
    networks:
      - kafkastreams-network

networks:
  kafkastreams-network:
    name: ks
