version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes


  kafka:
    image: 'docker.io/bitnami/kafka:3.2'
    restart: "no"
    ports:
      - '9092:9092'
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 1000

    depends_on:
      - zookeeper
      
