version: '3.5'

services:

  producer:
    image: rianmachado/native-producer-movie:latest  
    build:
      context: kafka-streams-producer
      dockerfile: src/main/docker/Dockerfile.native
    environment:
      KAFKA_BOOTSTRAP_SERVERS: localhost:9092
    networks:
      - kafkastreams-network

  aggregator:
    image: rianmachado/native-aggregator-movie:latest
    build:
      context: kafka-streams-aggregator
      dockerfile: src/main/docker/Dockerfile.native
    environment:
      QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS: localhost:9092
    networks:
      - kafkastreams-network

networks:
  kafkastreams-network:
    name: ks
