global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: producer
    metrics_path: /q/metrics
    static_configs:
      - targets:
          - '192.168.0.230:8080'
