FROM registry.fedoraproject.org/fedora-minimal
RUN microdnf -y install libxcrypt-compat && microdnf clean all
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Xmx32m"]
