version: '3'

services:
  prometheus-producer:
    image: prom/prometheus:v2.21.0
    ports:
      - 9091:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-producer-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml


volumes:
  prometheus-producer-data:


